export const BlogPosts = [
  {
    title: "¿Qué es poema?",
    subtitle: "– Lorenzo Gil Gill",
    introduction:
      "Iniciamos el 2020 alimentando nuestro blog Tejidos Textuales con un hermoso poema escrito por uno de nuestros colaboradores: Lorenzo Gil Gill indígena de la nación Wiwa (Arsario), Sierra Nevada de Santa Marta, que reside en Bogotá donde escribe, estudia y desde donde realiza numerosas actividades vinculadas con el turismo sostenible en su territorio ancestral. Nos complace compartir su reflexión sobre la poesía, un tema que hace parte esencial de la cultura de las tradiciones originarias que habitan el mundo de manera poética y nos enseñan a encontrar la poesía mas allá del texto escrito.",
    text:
      "A los 12 años sentí el primer zapatazo de mi corazón\nDescubrí el mundo de las palabras, cuando te encontré reposando en una flor\nEntendí que el mundo constituye de verbos y poemas\nQue las palabras mágicas crean ilusiones eternas\nQue podría vivir justo allí, en la dimensión etérea\nFue entonces que calqué realidades en sustantivos\nDibujé palabras en el viento\nRegué poemas en las olas del mar Tayrona\nMe enamoré en el mismo lugar donde nací\nComo un ritual de iniciación, encendí las llamas\nEsa llama que me mantiene vivo\nUna luz en el camino, una luz que llaman poemas\nAlgunos piensan que son meras palabras\nOtros que es símbolo del amor\nPara otros son emociones condensadas en palabras\nPara mí...\nDesde entonces vibra conmigo\nViaja en mi maleta con visa hacia la eternidad\nA veces lo descubro en el mismo lugar, en los pétalos\nOtras veces en las noches estrelladas\nOtras veces es en teorías, en libros viejos\nOtras veces en su mirar, en sus labios\nO cuando me esquivas esa mirada cimarrona pero enamorada\nY un par de veces,\ndepositada en el alma innata de una mujer enamorada ...\ncomo tú,\nPara mí, y nada más que para mí, un poema es el mismo silencio marchando a un lado del universo de las palabras, iluminando mentes atrevidas, forjando carácter en quien le descubre y describe para oídos sensatos,\nAlcanzo a verlo en una conversación\nLo aprecio en una tristeza fecunda\nLo identifico en un juego de palabras\nEstá en la espera de una madre a su hijo\nEn el respeto de los territorios\nEn pagamentos y en un suspiro\nPara mí...\nBajo árbol frondoso y con raíces al cielo\nEn un beso sincero y vital es un poema materializado\nComo la piedra tallada en siglos por los Tayronas\nMi amor forja un camino sin retorno hacia ti\nY que mejor que la misma esencia de la vida,\nun poema pueda gritar como un arte\nHaré que el mundo nazca y amanezca\nQue despunte un nuevo amanecer\nQue la tierra donde habitamos sea palabras corriendo desnudas hacia la vida misma,\narmonía y alineación\nUna perfecta sincronía entre tu pecho y mi corazón\nEntre palabras e historias,\nentre la tuya amor y la mía...",
    footerHeader: "Lorenzo Gill",
    footerHeaderLink: "https://lorenzogill.wordpress.com/",
    footerText:
      "Etnia Wiwa y Kogui\nDirector de la Fundación Wiwa\nUniversidad Externado de Colombia\nSierra Nevada de Santa Marta\nColombia",
  },
];
